### ISSUE TITLE
Does not work with UNIX sockets.

### ISSUE THREAD

**Issue by 8h2a** [cjlucas/rtorrent-python#14]
When i try to connect via a unix socket I get a NotImplementedError:

`.../rtorrent/__init__.py", line 71, in __init__`
`raise NotImplementedError()`

I'm running the latest version from source.

**Comment by NotZappy** [comment]
You need to use the `scgi` protocol. This code works fine for me:

``` python
import rtorrent
socket_file = '/path/to/socket'
client = rtorrent.RTorrent('scgi://' + socket_file)
```

**Comment by 8h2a** [comment]
Thanks!
(issue can be closed now)
